package io.swagger.configuration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/*
import springfox.documentation.service.Contact;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.service.ApiInfo;*/
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-06-12T02:03:20.587Z[GMT]")
@Configuration
public class SwaggerDocumentationConfig {
/*
    @Bean
    public Docket customImplementation(){
        return new Docket(DocumentationType.OAS_30)
                .select()
                    .apis(RequestHandlerSelectors.basePackage("io.swagger.api"))
                    .build()
                .directModelSubstitute(org.threeten.bp.LocalDate.class, java.sql.Date.class)
                .directModelSubstitute(org.threeten.bp.OffsetDateTime.class, java.util.Date.class)
                .apiInfo(apiInfo());
    }

    ApiInfo apiInfo() {
        return new ApiInfoBuilder()
            .title("pruebaApiRest")
            .description("No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)")
            .license("Apache 2.0")
            .licenseUrl("https://www.gnu.org/licenses/gpl-3.0.html")
            .termsOfServiceUrl("https://www.linkedin.com/in/c%C3%A9sar-augusto-garc%C3%ADa-cortez-7a85a958")
            .version("1.0")
            .contact(new Contact("","", "cagc1993@hotmail.com"))
            .build();
    }*/

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI()
            .info(new Info()
                .title("pruebaApiRest")
                .description("No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)")
                .termsOfService("https://www.linkedin.com/in/c%C3%A9sar-augusto-garc%C3%ADa-cortez-7a85a958")
                .version("1.0")
                .license(new License()
                    .name("Apache 2.0")
                    .url("https://www.gnu.org/licenses/gpl-3.0.html"))
                .contact(new io.swagger.v3.oas.models.info.Contact()
                    .email("cagc1993@hotmail.com")));
    }

}
